name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mumumusf
          gif_out_path: dist/github-snake.gif
          svg_out_path: dist/github-snake.svg
          
      - uses: Platane/snk@master
        id: snake-dark
        with:
          github_user_name: mumumusf
          gif_out_path: dist/github-snake-dark.gif
          svg_out_path: dist/github-snake-dark.svg
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.svg?palette=github-light
          
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: output
          message: 'Generate Contribution Snake'